// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWo0qSGm-gLiapdsgt_PZpDmSS9ffB7XQ',
    appId: '1:1001982996551:web:eadc6ac85abe83c5d7c162',
    messagingSenderId: '1001982996551',
    projectId: 'chat-app-flutter-5ac24',
    authDomain: 'chat-app-flutter-5ac24.firebaseapp.com',
    databaseURL: 'https://chat-app-flutter-5ac24-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-flutter-5ac24.firebasestorage.app',
    measurementId: 'G-R4FY2X4496',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmlO7hfp6B5f53MBVgFCSgmAn2aL2rw0w',
    appId: '1:1001982996551:android:4f96700493c1c4b6d7c162',
    messagingSenderId: '1001982996551',
    projectId: 'chat-app-flutter-5ac24',
    databaseURL: 'https://chat-app-flutter-5ac24-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-flutter-5ac24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpUlY2P4VzXpcJnBxjFU3DfgTVfgugwT0',
    appId: '1:1001982996551:ios:3e24abd3610566d5d7c162',
    messagingSenderId: '1001982996551',
    projectId: 'chat-app-flutter-5ac24',
    databaseURL: 'https://chat-app-flutter-5ac24-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-flutter-5ac24.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpUlY2P4VzXpcJnBxjFU3DfgTVfgugwT0',
    appId: '1:1001982996551:ios:3e24abd3610566d5d7c162',
    messagingSenderId: '1001982996551',
    projectId: 'chat-app-flutter-5ac24',
    databaseURL: 'https://chat-app-flutter-5ac24-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-flutter-5ac24.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWo0qSGm-gLiapdsgt_PZpDmSS9ffB7XQ',
    appId: '1:1001982996551:web:ddd9dce1ddfb220cd7c162',
    messagingSenderId: '1001982996551',
    projectId: 'chat-app-flutter-5ac24',
    authDomain: 'chat-app-flutter-5ac24.firebaseapp.com',
    databaseURL: 'https://chat-app-flutter-5ac24-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-flutter-5ac24.firebasestorage.app',
    measurementId: 'G-BZ2ZK9H9BT',
  );
}
